/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.intecap.veterinaria.gui;

import co.edu.intecap.veterinaria.negocio.Mascota;
import co.edu.intecap.veterinaria.negocio.mascotas.Gato;
import co.edu.intecap.veterinaria.negocio.mascotas.Perro;

/**
 *
 * @author Capacitaciones
 */
public class Visualizador extends javax.swing.JDialog {

    private Perro perro;
    private Gato gato;

    /**
     * Creates new form Visualizador
     */
    public Visualizador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Visualizador(java.awt.Frame parent, boolean modal, Perro perro) {
        super(parent, modal);
        initComponents();
        this.perro = perro;
        pnDetallePerro.setVisible(false);

        pnDetalleGato.setVisible(false);
        this.mostrarInformacion();
    }

    public Visualizador(java.awt.Frame parent, boolean modal, Gato gato) {
        super(parent, modal);
        initComponents();
        this.gato = gato;
        pnDetallePerro.setVisible(false);

        pnDetalleGato.setVisible(false);
        this.mostrarInformacion();
    }

    private void mostrarInformacion() {
        Mascota mascota = null;
        if (this.perro != null) {
            mascota = this.perro;
            pnDetallePerro.setVisible(true);

            pnDetalleGato.setVisible(false);
            txtDetalleColor.setBackground(this.perro.getCOLOR());
            lblDetalleTamano.setText(this.perro.getTamano() + " cm");
            lblDetalleCola.setText(this.perro.isCola() ? "cola larga" : "cola corta");

        }
        if (this.gato != null) {
            mascota = this.gato;

            pnDetallePerro.setVisible(false);

            pnDetalleGato.setVisible(true);
            lblDetallePelo.setText(this.gato.isPelo() ? "pelo largo" : "pelo corto");
            lblDetalleGarras.setText(this.gato.isGarras() ? "garras largas" : "garras cortas");
        }

        lblDetalleNombre.setText(mascota.getNombre());
        lblDetalleEdad.setText(mascota.getEdad() + " años");
        lblDetallePeso.setText(mascota.getPeso() + "kilogramos");
        lblDetalleRaza.setText(mascota.getRaza());
        lblDetalledueno.setText(mascota.getDueno());
        lblDetalleEnergia.setText(mascota.getEnergia() + " ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnDetallePerro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDetalleTamano = new javax.swing.JLabel();
        txtDetalleColor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblDetalleCola = new javax.swing.JLabel();
        pnDetalleGato = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblDetallePelo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblDetalleGarras = new javax.swing.JLabel();
        lblDetalleNombre = new javax.swing.JLabel();
        lblDetalleEdad = new javax.swing.JLabel();
        lblDetallePeso = new javax.swing.JLabel();
        lblDetalleRaza = new javax.swing.JLabel();
        lblDetalledueno = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        lblDetalleEnergia = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Edad:");

        jLabel3.setText("Peso:");

        jLabel5.setText("Raza:");

        jLabel6.setText("Dueño:");

        jLabel7.setText("Tamaño:");

        jLabel8.setText("Color:");

        lblDetalleTamano.setText("tamaño");

        txtDetalleColor.setEditable(false);

        jLabel10.setText("Cola:");

        lblDetalleCola.setText("cola");

        javax.swing.GroupLayout pnDetallePerroLayout = new javax.swing.GroupLayout(pnDetallePerro);
        pnDetallePerro.setLayout(pnDetallePerroLayout);
        pnDetallePerroLayout.setHorizontalGroup(
            pnDetallePerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetallePerroLayout.createSequentialGroup()
                .addGroup(pnDetallePerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetallePerroLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDetalleTamano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnDetallePerroLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtDetalleColor)))
                .addGap(10, 10, 10))
            .addGroup(pnDetallePerroLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(22, 22, 22)
                .addComponent(lblDetalleCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnDetallePerroLayout.setVerticalGroup(
            pnDetallePerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetallePerroLayout.createSequentialGroup()
                .addGroup(pnDetallePerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDetalleTamano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetallePerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDetalleColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetallePerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblDetalleCola)))
        );

        jLabel9.setText("Pelo:");

        lblDetallePelo.setText("pelo");

        jLabel11.setText("Garras");

        lblDetalleGarras.setText("garras");

        javax.swing.GroupLayout pnDetalleGatoLayout = new javax.swing.GroupLayout(pnDetalleGato);
        pnDetalleGato.setLayout(pnDetalleGatoLayout);
        pnDetalleGatoLayout.setHorizontalGroup(
            pnDetalleGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetalleGatoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnDetalleGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetalleGatoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblDetallePelo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDetalleGatoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDetalleGarras)))
                .addContainerGap())
        );
        pnDetalleGatoLayout.setVerticalGroup(
            pnDetalleGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetalleGatoLayout.createSequentialGroup()
                .addGroup(pnDetalleGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblDetallePelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetalleGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblDetalleGarras)))
        );

        lblDetalleNombre.setText("nombre");

        lblDetalleEdad.setText("edad");

        lblDetallePeso.setText("peso");

        lblDetalleRaza.setText("raza");

        lblDetalledueno.setText("dueño");

        btnAceptar.setText("Aceptar");

        lblDetalleEnergia.setText("Energia");

        jLabel12.setText("Energia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDetallePerro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDetalleNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblDetalleEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDetalledueno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblDetalleRaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblDetallePeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addComponent(pnDetalleGato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDetalleEnergia)
                .addGap(210, 210, 210)
                .addComponent(btnAceptar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDetalleNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDetalleEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDetallePeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDetalleRaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDetalledueno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDetallePerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnDetalleGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(lblDetalleEnergia)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDetalleCola;
    private javax.swing.JLabel lblDetalleEdad;
    private javax.swing.JLabel lblDetalleEnergia;
    private javax.swing.JLabel lblDetalleGarras;
    private javax.swing.JLabel lblDetalleNombre;
    private javax.swing.JLabel lblDetallePelo;
    private javax.swing.JLabel lblDetallePeso;
    private javax.swing.JLabel lblDetalleRaza;
    private javax.swing.JLabel lblDetalleTamano;
    private javax.swing.JLabel lblDetalledueno;
    private javax.swing.JPanel pnDetalleGato;
    private javax.swing.JPanel pnDetallePerro;
    private javax.swing.JTextField txtDetalleColor;
    // End of variables declaration//GEN-END:variables
}
